name = "Test"
filename = "my_demo.wav"
bpm = 180.0
beat_par_bar = 4

length = 65.0

notes = [
    # intro
    { bar = 0, beat = 0, key_column = 0 },
    { bar = 0, beat = 1, key_column = 0 },
    { bar = 0, beat = 2, key_column = 0 },
    { bar = 0, beat = 2.5, key_column = 1 },
    { bar = 0, beat = 2.75, key_column = 2 },
    { bar = 0, beat = 3, key_column = 3 },

    { bar = 1, beat = 0, key_column = 0 },
    { bar = 1, beat = 0, key_column = 1 },
    { bar = 1, beat = 0, key_column = 2 },
    { bar = 1, beat = 0, key_column = 3 },
    { bar = 1, beat = 2.5, key_column = 1 },
    { bar = 1, beat = 3.5, key_column = 3 },
    { bar = 2, beat = 0.5, key_column = 0 },
    { bar = 2, beat = 1.5, key_column = 2 },
    { bar = 2, beat = 2.5, key_column = 0 },

    { bar = 3, beat = 0, key_column = 3 },
    { bar = 3, beat = 2.5, key_column = 1 },
    { bar = 3, beat = 3.5, key_column = 3 },
    { bar = 4, beat = 0.5, key_column = 0 },
    { bar = 4, beat = 1.5, key_column = 2 },
    { bar = 4, beat = 2.5, key_column = 3 },
    { bar = 4, beat = 3, key_column = 0 },
    { bar = 4, beat = 3.5, key_column = 1 },

    { bar = 5, beat = 0, key_column = 0 },
    { bar = 5, beat = 0, key_column = 1 },
    { bar = 5, beat = 0, key_column = 2 },
    { bar = 5, beat = 0, key_column = 3 },
    { bar = 5, beat = 2.5, key_column = 1 },
    { bar = 5, beat = 3.5, key_column = 3 },
    { bar = 6, beat = 0.5, key_column = 0 },
    { bar = 6, beat = 1.5, key_column = 2 },
    { bar = 6, beat = 2.5, key_column = 0 },

    { bar = 7, beat = 0, key_column = 3 },
    { bar = 7, beat = 2.5, key_column = 1 },
    { bar = 7, beat = 3.5, key_column = 2 },
    { bar = 7, beat = 3.5, key_column = 3 },
    { bar = 8, beat = 0.5, key_column = 1 },
    { bar = 8, beat = 0.5, key_column = 2 },
    { bar = 8, beat = 1.5, key_column = 0 },
    { bar = 8, beat = 1.5, key_column = 1 },
    { bar = 8, beat = 2.5, key_column = 0 },
    { bar = 8, beat = 2.5, key_column = 3 },
    { bar = 8, beat = 3, key_column = 1 },
    { bar = 8, beat = 3, key_column = 2 },

    # A part
    { bar = 9, beat = 0, key_column = 2 },
    { bar = 9, beat = 0, key_column = 3 },
    { bar = 9, beat = 1, key_column = 0 },
    { bar = 9, beat = 1.5, key_column = 0 },
    { bar = 9, beat = 2, key_column = 0 },
    { bar = 9, beat = 2.5, key_column = 0 },
    { bar = 9, beat = 3, key_column = 0 },
    { bar = 9, beat = 3.5, key_column = 0 },
    { bar = 10, beat = 0, key_column = 0 },
    { bar = 10, beat = 0.5, key_column = 0 },
    { bar = 10, beat = 1, key_column = 0 },
    { bar = 10, beat = 1.5, key_column = 0 },
    { bar = 10, beat = 2, key_column = 3 },
    { bar = 10, beat = 2.5, key_column = 2 },
    { bar = 10, beat = 3, key_column = 1 },
    { bar = 10, beat = 3.5, key_column = 0 },
    { bar = 11, beat = 0.5, key_column = 0 },
    { bar = 11, beat = 1, key_column = 0 },
    { bar = 11, beat = 1.5, key_column = 0 },
    { bar = 11, beat = 2, key_column = 0 },
    { bar = 11, beat = 2.5, key_column = 0 },
    { bar = 11, beat = 3, key_column = 0 },
    { bar = 11, beat = 3.5, key_column = 0 },
    { bar = 11, beat = 3.5, key_column = 1 },
    { bar = 12, beat = 0.5, key_column = 2 },
    { bar = 12, beat = 0.5, key_column = 3 },
    { bar = 12, beat = 1.5, key_column = 1 },
    { bar = 12, beat = 1.5, key_column = 2 },
    { bar = 12, beat = 2.5, key_column = 0 },
    { bar = 12, beat = 2.5, key_column = 1 },
    { bar = 12, beat = 3.5, key_column = 3 },
    { bar = 12, beat = 3.75, key_column = 3 },

    { bar = 13, beat = 0, key_column = 2 },
    { bar = 13, beat = 1, key_column = 0 },
    { bar = 13, beat = 1.5, key_column = 0 },
    { bar = 13, beat = 2, key_column = 0 },
    { bar = 13, beat = 2.5, key_column = 0 },
    { bar = 13, beat = 3, key_column = 0 },
    { bar = 13, beat = 3.5, key_column = 0 },
    { bar = 14, beat = 0, key_column = 0 },
    { bar = 14, beat = 0.5, key_column = 0 },
    { bar = 14, beat = 1, key_column = 0 },
    { bar = 14, beat = 1.5, key_column = 0 },
    { bar = 14, beat = 2, key_column = 3 },
    { bar = 14, beat = 2.5, key_column = 2 },
    { bar = 14, beat = 3, key_column = 1 },
    { bar = 14, beat = 3.5, key_column = 0 },
    { bar = 15, beat = 0.5, key_column = 0 },
    { bar = 15, beat = 1, key_column = 0 },
    { bar = 15, beat = 1.5, key_column = 0 },
    { bar = 15, beat = 2, key_column = 0 },
    { bar = 15, beat = 2.5, key_column = 0 },
    { bar = 15, beat = 3, key_column = 0 },
    { bar = 15, beat = 3.5, key_column = 0 },
    { bar = 16, beat = 0, key_column = 0 },
    { bar = 16, beat = 0, key_column = 1 },
    { bar = 16, beat = 0.5, key_column = 0 },
    { bar = 16, beat = 0.5, key_column = 1 },
    { bar = 16, beat = 2, key_column = 2 },
    { bar = 16, beat = 2, key_column = 3 },
    { bar = 16, beat = 2.5, key_column = 0 },
    { bar = 16, beat = 2.5, key_column = 1 },
    { bar = 16, beat = 3, key_column = 0 },
    { bar = 16, beat = 3.25, key_column = 1 },
    { bar = 16, beat = 3.5, key_column = 2 },
    { bar = 16, beat = 3.75, key_column = 3 },

    # b part
    { bar = 17, beat = 0.0, key_column = 3 },
    { bar = 17, beat = 0.25, key_column = 2 },
    { bar = 17, beat = 0.5, key_column = 3 },
    { bar = 17, beat = 0.75, key_column = 2 },
    { bar = 17, beat = 1.0, key_column = 3 },
    { bar = 17, beat = 1.5, key_column = 3 },
    { bar = 17, beat = 2.0, key_column = 2 },
    { bar = 17, beat = 2.5, key_column = 1 },
    { bar = 17, beat = 3.0, key_column = 0 },
    { bar = 17, beat = 3.5, key_column = 0 },
    { bar = 18, beat = 0.5, key_column = 3 },
    { bar = 18, beat = 1.0, key_column = 2 },
    { bar = 18, beat = 1.5, key_column = 1 },
    { bar = 18, beat = 2.0, key_column = 0 },
    { bar = 18, beat = 2.5, key_column = 1 },
    { bar = 18, beat = 3.0, key_column = 2 },
    { bar = 18, beat = 3.5, key_column = 3 },
    { bar = 19, beat = 0.5, key_column = 0 },
    { bar = 19, beat = 1.5, key_column = 2 },
    { bar = 19, beat = 2.5, key_column = 1 },
    { bar = 19, beat = 3.5, key_column = 2 },
    { bar = 19, beat = 3.5, key_column = 3 },
    { bar = 20, beat = 0.5, key_column = 0 },
    { bar = 20, beat = 0.5, key_column = 1 },
    { bar = 20, beat = 1.5, key_column = 1 },
    { bar = 20, beat = 2.5, key_column = 2 },
    { bar = 20, beat = 3.0, key_column = 1 },
    { bar = 20, beat = 3.5, key_column = 2 },

    # c part
    { bar = 21, beat = 0, key_column = 0 },
    { bar = 21, beat = 0, key_column = 1 },
    { bar = 21, beat = 0, key_column = 2 },
    { bar = 21, beat = 0, key_column = 3 },
    { bar = 21, beat = 1, key_column = 0 },
    { bar = 21, beat = 2, key_column = 1 },
    { bar = 21, beat = 2.5, key_column = 3 },
    { bar = 21, beat = 3.5, key_column = 2 },
    { bar = 22, beat = 1, key_column = 0 },
    { bar = 22, beat = 1.5, key_column = 1 },
    { bar = 22, beat = 2, key_column = 2 },
    { bar = 22, beat = 2, key_column = 3 },
    { bar = 22, beat = 2.5, key_column = 0 },
    { bar = 22, beat = 2.5, key_column = 1 },
    { bar = 22, beat = 3, key_column = 2 },
    { bar = 22, beat = 3, key_column = 3 },
    { bar = 22, beat = 3.5, key_column = 0 },
    { bar = 22, beat = 3.5, key_column = 1 },

    { bar = 23, beat = 0, key_column = 0 },
    { bar = 23, beat = 0.25, key_column = 1 },
    { bar = 23, beat = 0.5, key_column = 0 },
    { bar = 23, beat = 1, key_column = 0 },
    { bar = 23, beat = 2, key_column = 1 },
    { bar = 23, beat = 2.5, key_column = 3 },
    { bar = 23, beat = 3.5, key_column = 2 },
    { bar = 24, beat = 0.5, key_column = 0 },
    { bar = 24, beat = 1.5, key_column = 1 },
    { bar = 24, beat = 2, key_column = 0 },
    { bar = 24, beat = 2, key_column = 2 },
    { bar = 24, beat = 2.5, key_column = 1 },
    { bar = 24, beat = 3, key_column = 2 },
    { bar = 24, beat = 3.5, key_column = 3 },

    { bar = 25, beat = 0, key_column = 0 },
    { bar = 25, beat = 0, key_column = 1 },
    { bar = 25, beat = 0, key_column = 2 },
    { bar = 25, beat = 0, key_column = 3 },
    { bar = 25, beat = 1, key_column = 0 },
    { bar = 25, beat = 2, key_column = 1 },
    { bar = 25, beat = 2.5, key_column = 3 },
    { bar = 25, beat = 3.5, key_column = 2 },
    { bar = 26, beat = 1.5, key_column = 1 },
    { bar = 26, beat = 2, key_column = 2 },
    { bar = 26, beat = 2.5, key_column = 3 },
    { bar = 26, beat = 3, key_column = 1 },
    { bar = 26, beat = 3.5, key_column = 2 },

    { bar = 27, beat = 0.5, key_column = 0 },
    { bar = 27, beat = 1, key_column = 3 },
    { bar = 27, beat = 1.5, key_column = 2 },
    { bar = 27, beat = 2, key_column = 3 },
    { bar = 27, beat = 2.5, key_column = 2 },
    { bar = 27, beat = 3, key_column = 3 },
    { bar = 27, beat = 3.5, key_column = 2 },
    { bar = 28, beat = 0, key_column = 3 },
    { bar = 28, beat = 0.5, key_column = 2 },
    { bar = 28, beat = 1, key_column = 3 },
    # 混フレ
    { bar = 26, beat = 1.5, key_column = 1 },
    { bar = 26, beat = 2, key_column = 2 },
    { bar = 26, beat = 2.5, key_column = 0 },
    { bar = 26, beat = 3, key_column = 2 },
    { bar = 26, beat = 3.5, key_column = 1 },
    { bar = 27, beat = 3, key_column = 0 },
    { bar = 27, beat = 3.5, key_column = 1 },
    { bar = 28, beat = 0.5, key_column = 0 },
    { bar = 28, beat = 1, key_column = 1 },
    { bar = 28, beat = 1.75, key_column = 2 },
    { bar = 28, beat = 2, key_column = 0 },
    { bar = 28, beat = 2.5, key_column = 2 },
    { bar = 28, beat = 2.75, key_column = 1 },
    { bar = 28, beat = 3, key_column = 2 },
    { bar = 28, beat = 3.25, key_column = 1 },
    { bar = 28, beat = 3.5, key_column = 2 },
    { bar = 28, beat = 3.75, key_column = 1 },

    # c part 2
    { bar = 29, beat = 0, key_column = 2 },
    { bar = 29, beat = 0, key_column = 3 },
    { bar = 29, beat = 1, key_column = 0 },
    { bar = 29, beat = 2, key_column = 1 },
    { bar = 29, beat = 2.5, key_column = 3 },
    { bar = 29, beat = 3.5, key_column = 2 },
    { bar = 30, beat = 1, key_column = 0 },
    { bar = 30, beat = 1.5, key_column = 1 },
    { bar = 30, beat = 2, key_column = 2 },
    { bar = 30, beat = 2, key_column = 3 },
    { bar = 30, beat = 2.5, key_column = 0 },
    { bar = 30, beat = 2.5, key_column = 1 },
    { bar = 30, beat = 3, key_column = 2 },
    { bar = 30, beat = 3, key_column = 3 },
    { bar = 30, beat = 3.5, key_column = 0 },
    { bar = 30, beat = 3.5, key_column = 1 },

    { bar = 31, beat = 0, key_column = 0 },
    { bar = 31, beat = 0.25, key_column = 1 },
    { bar = 31, beat = 0.5, key_column = 0 },
    { bar = 31, beat = 1, key_column = 0 },
    { bar = 31, beat = 2, key_column = 1 },
    { bar = 31, beat = 2.5, key_column = 3 },
    { bar = 31, beat = 3.5, key_column = 2 },
    { bar = 32, beat = 0.5, key_column = 0 },
    { bar = 32, beat = 1.5, key_column = 1 },
    { bar = 32, beat = 2, key_column = 0 },
    { bar = 32, beat = 2, key_column = 2 },
    { bar = 32, beat = 2.5, key_column = 1 },
    { bar = 32, beat = 3, key_column = 2 },
    { bar = 32, beat = 3.5, key_column = 3 },

    { bar = 33, beat = 0, key_column = 0 },
    { bar = 33, beat = 0, key_column = 1 },
    { bar = 33, beat = 0, key_column = 2 },
    { bar = 33, beat = 0, key_column = 3 },
    { bar = 33, beat = 1, key_column = 0 },
    { bar = 33, beat = 2, key_column = 1 },
    { bar = 33, beat = 2.5, key_column = 3 },
    { bar = 33, beat = 3.5, key_column = 2 },
    { bar = 34, beat = 1.5, key_column = 1 },
    { bar = 34, beat = 2, key_column = 2 },
    { bar = 34, beat = 2.5, key_column = 3 },
    { bar = 34, beat = 3, key_column = 1 },
    { bar = 34, beat = 3.5, key_column = 2 },

    { bar = 35, beat = 0.5, key_column = 0 },
    { bar = 35, beat = 1, key_column = 3 },
    { bar = 35, beat = 1.5, key_column = 2 },
    { bar = 35, beat = 2, key_column = 3 },
    { bar = 35, beat = 2.5, key_column = 2 },
    { bar = 35, beat = 3, key_column = 3 },
    { bar = 35, beat = 3.5, key_column = 2 },
    { bar = 36, beat = 0, key_column = 3 },
    { bar = 36, beat = 0.5, key_column = 2 },
    { bar = 36, beat = 1, key_column = 3 },
    # 混フレ
    { bar = 34, beat = 1.5, key_column = 1 },
    { bar = 34, beat = 2, key_column = 2 },
    { bar = 34, beat = 2.5, key_column = 0 },
    { bar = 34, beat = 3, key_column = 2 },
    { bar = 34, beat = 3.5, key_column = 1 },
    { bar = 35, beat = 3, key_column = 0 },
    { bar = 35, beat = 3.5, key_column = 1 },
    { bar = 36, beat = 0.5, key_column = 0 },
    { bar = 36, beat = 1, key_column = 2 },
    { bar = 36, beat = 1.75, key_column = 1 },
    { bar = 36, beat = 2, key_column = 0 },
    { bar = 36, beat = 2.5, key_column = 2 },
    { bar = 36, beat = 2.75, key_column = 1 },
    { bar = 36, beat = 3, key_column = 2 },
    { bar = 36, beat = 3.25, key_column = 1 },
    { bar = 36, beat = 3.5, key_column = 2 },
    { bar = 36, beat = 3.75, key_column = 1 },

    # out
    { bar = 37, beat = 0, key_column = 0 },
    { bar = 37, beat = 0, key_column = 1 },
    { bar = 37, beat = 0, key_column = 2 },
    { bar = 37, beat = 0, key_column = 3 },
    { bar = 37, beat = 2.5, key_column = 1 },
    { bar = 37, beat = 3.5, key_column = 3 },
    { bar = 38, beat = 0.5, key_column = 0 },
    { bar = 38, beat = 1.5, key_column = 2 },
    { bar = 38, beat = 2.5, key_column = 0 },

    { bar = 39, beat = 0, key_column = 3 },
    { bar = 39, beat = 2.5, key_column = 1 },
    { bar = 39, beat = 3.5, key_column = 3 },
    { bar = 40, beat = 0.5, key_column = 0 },
    { bar = 40, beat = 1.5, key_column = 2 },
    { bar = 40, beat = 2.5, key_column = 3 },
    { bar = 40, beat = 3, key_column = 0 },
    { bar = 40, beat = 3.5, key_column = 1 },

    { bar = 41, beat = 0, key_column = 0 },
    { bar = 41, beat = 0, key_column = 1 },
    { bar = 41, beat = 0, key_column = 2 },
    { bar = 41, beat = 0, key_column = 3 },
    { bar = 41, beat = 2.5, key_column = 1 },
    { bar = 41, beat = 3.5, key_column = 3 },
    { bar = 42, beat = 0.5, key_column = 0 },
    { bar = 42, beat = 1.5, key_column = 2 },
    { bar = 42, beat = 2.5, key_column = 0 },

    { bar = 43, beat = 0, key_column = 3 },
    { bar = 43, beat = 2.5, key_column = 1 },
    { bar = 43, beat = 3.5, key_column = 2 },
    { bar = 43, beat = 3.5, key_column = 3 },
    { bar = 44, beat = 0.5, key_column = 1 },
    { bar = 44, beat = 0.5, key_column = 2 },
    { bar = 44, beat = 1.5, key_column = 0 },
    { bar = 44, beat = 1.5, key_column = 1 },
    { bar = 44, beat = 2.5, key_column = 0 },
    { bar = 44, beat = 2.5, key_column = 3 },
    { bar = 44, beat = 3.5, key_column = 1 },
    { bar = 44, beat = 3.5, key_column = 2 },
    { bar = 45, beat = 0, key_column = 0 },
    { bar = 45, beat = 0, key_column = 1 },
    { bar = 45, beat = 0, key_column = 2 },
    { bar = 45, beat = 0, key_column = 3 },

    { bar = 45, beat = 3.5, key_column = 3 },
    { bar = 45, beat = 3.66667, key_column = 2 },
    { bar = 45, beat = 3.83333, key_column = 1 },
    { bar = 46, beat = 0, key_column = 0 },
]
